ts_class
KangoKishino/ts_class pull request #1
Opened 2021-05-08 01:12 UTC by KangoKishino

2021-05-08 10:27 UTC, myzktkyk reviewed
レビューいたしました。
所々「コピー」というキーワードが出てくるかと思いますが、ライブラリを用いると簡単に実装ができます。
おススメなのは ramda.js です。
https://ramdajs.com/
https://tech.recruit-mp.co.jp/front-end/post-16249/

2021-05-08 10:27 UTC, myzktkyk commented on src/index.ts
> +    this._obj = _obj;
`引数のオブジェクトのコピーを this._objに設定` というコメントの通り
オブジェクトのコピーが設定されるようにしてください。

2021-05-08 10:27 UTC, myzktkyk commented on src/index.ts
> +    return this._obj;
こちらに関しても「オブジェクトのコピーが返却」されるように改修してみてください。

2021-05-08 10:27 UTC, myzktkyk commented on src/index.ts
> +  set(key: string, val: string): boolean {
これでもある程度型安全になっていますが、もう少し汎用的になるように頑張ってみてほしいです。
ヒントは `ジェネリクス` です。
https://typescript-jp.gitbook.io/deep-dive/type-system/type-compatibility#jenerikusugenerics

2021-05-08 10:27 UTC, myzktkyk commented on src/index.ts
> +class ObjectWrapper {
`ObjectWrapper `をインスタンス化した時に型を指定できるように
ジェネリクスを用いてほしいです。

2021-05-08 10:27 UTC, myzktkyk commented on src/index.ts
> +        return this._obj[key];
`指定したキーの値のコピーを返却` というコメントの通りとなるように
コピーを返却できるようにしてみましょう。

2021-05-11 12:58 UTC, myzktkyk requested changes
指摘の対応ありがとうございます！
とても惜しいのですがもういくつか、指摘があります。
ゴールは目前なので、もう少しだけ頑張ってみてください！

2021-05-11 12:58 UTC, myzktkyk commented on src/index.ts
> +class ObjectWrapper<T, U> implements A<T, U> {
こちら https://github.com/KangoKishino/ts_class/pull/1#discussion_r628733060 を受けての修正だと思うのですが
ちょっとアプローチが異なります…。

`class ObjectWrapper<T extends object>`

とすることで、クラス内に `T` という型引数が定義できます。

2021-05-11 12:58 UTC, myzktkyk commented on src/index.ts
> +  constructor(_obj: Object) {
クラス宣言のところで型引数を宣言すると、コンストラクタは以下のようにできます

`constructor(obj: T) {`

ここでは `T` はクラス宣言をした場所での記載 `T extends object` の通り
「オブジェクトを継承したクラスである」という制限がかかります。

2021-05-11 12:58 UTC, myzktkyk commented on src/index.ts
> +        return this._obj[copyKey];
最初のレビューの時に見落としてしまいましたが…
これでは「コピーしたキーを使って、コピーしていない値を返す」ことになってます。
題意は「引数として受けっとたキーでオブジェクトから値を取り出す。取り出した値はコピーした値を返すこと」です。

2021-05-11 12:58 UTC, myzktkyk commented on src/index.ts
> +  set(key: T, val: U): boolean {
`extends keyof` というキーワードがあります。
これを使って以下のように記述します。

`set<K extends keyof T>(key: K, val: T[K]): boolean {`

すると `K` は「 `T` というオブジェクトに存在するキー」という制限を付けることができます。
https://negalog.com/typescript-keyof-generics/

2021-05-11 12:58 UTC, myzktkyk commented on src/index.ts
> +}
`set` のところでコメントした通り `extends keyof` を利用するとこちらは不要にできるはずです。

2021-05-11 12:58 UTC, myzktkyk commented on src/index.ts
> +    const objCopy = R.clone(this._obj);
ramda.js の使い方はばっちりですね！

2021-05-12 06:38 UTC, yoshin04 commented on dist/index.js
> +}
distはコンパイル後自動生成されますので、gitの追跡には含めないようにするのがTSの基本になります。
今後は、.gitignoreにdistも設定するようにしましょう(^^)

2021-05-12 06:38 UTC, yoshin04 commented on src/index.ts
> +    }
引数にオブジェクトのkey型、valにオブジェクトの値型を指定しています。
よって、falseになる前に型エラーとなります。
つまり、この記述そのものが不要となります。

2021-05-12 06:38 UTC, yoshin04 commented on src/index.ts
> +    }
こちらのfor文はなぜ必要なのでしょうか？
keyにはオブジェクトのkey型しか入ってこないことは、関数の引数で指定済みのはずです。

2021-05-12 06:38 UTC, yoshin04 commented on src/index.ts
> +    }
このfor文自体が不要になります。
こちらもgetにオブジェクトのkeyが入るようにすればこの記述自体が不要になります。

2021-05-12 06:38 UTC, yoshin04 commented on src/index.ts
> +    }
> 指定のキーが存在しない場合 undefinedを返却

この記述でわかりにくくなっていますが、型安全を考えるとgetにはオブジェクトのkey以外入ってくること以外ありえないようにすれば、undefinedになる可能性も潰せるので、この記述も不要になります。

2021-05-12 06:38 UTC, yoshin04 commented on src/index.ts
> +  findKeys(val: unknown) {
> 該当のものがなければ空の配列を返却。

こちらの記述でこのようにしたと思いますが、TypeScritptの型安全を考えるとこの空の配列というのを無視しましょう！
valにunknown型を指定するとなんでも入ってしまうので、極力使用は避けたいです。

指定した値を持つkeyの配列を返却する条件に絶対なるように関数の引数と返す値の型を指定するようにしましょう！

2021-05-12 06:38 UTC, yoshin04 commented on src/index.ts
> +  }
関数の指定の仕方が変わりますので、ここの記述も変わると思います。
おそらく指定した値を持つkeyの配列を作るのに苦戦すると思います。
ですので一点ヒントなのですが、オブジェクトのkeyの配列を作るときにはRamdaのkeyというのを使用すると楽にできます。

2021-05-15 03:42 UTC, myzktkyk reviewed
非常に惜しいのですが、一点だけ指摘があります！

2021-05-15 03:42 UTC, myzktkyk commented on src/index.ts
> +    return true;
コメントにある `keyがthis._objに存在しない場合、falseを返却` が満たせていないように思います。

2021-05-16 11:58 UTC, yoshin04 commented
動作的には問題ないですので、OKです。
前回のコメントで、
> コメントにある keyがthis._objに存在しない場合、falseを返却 が満たせていないように思います。

上記のようにコメントされたと思うのですが、岸野さんの型定義の場合falseになる値が引数に入ってくることがないです。
ですので、仕様上falseを返却と書いているのですが、型エラーで防がれてしまうのでfalseの条件分岐は記述しなくてもOKです。
```
set<K extends keyof T>(key: K, val: T[K]): boolean {
```
コメントの意見が重なってしまいましたが、そもそもその値が入らないようにするというのが、型安全を実現しておく上で非常に重要になります。
ですので、これからTypeScriptで型定義をしていく上では1つ前の提出していただいたときの意識でいると良いかと思います。

2021-05-16 22:49 UTC, merged